src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TodoRepository::class)]
class Todo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $end_date = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo_src = null;

    #[ORM\Column(length: 64)]
    private ?string $status = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column]
    private ?int $user_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEndDate(): ?string
    {
        return $this->end_date;
    }

    public function setEndDate(string $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPhotoSrc(): ?string
    {
        return $this->photo_src;
    }

    public function setPhotoSrc(?string $photo_src): self
    {
        $this->photo_src = $photo_src;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('end_date', DateType::class, [
                'label' => 'Ajouter une tâche',
                'widget' => 'single_text',
                'input' => 'string'
            ])
            ->add('title', TextType::class, [
                'label' => 'Titre'
            ])
            ->add('description', TextareaType::class, [
                'attr' => ['rows' => 5],
                'label' => 'La description'
            ])
            ->add('status', ChoiceType::class, [
                'choices'=> [
                    'Pending' => 'pending', 
                    'In progress' => 'inprogress', 
                    'Completed' => 'completed'
                ],
                'label' => 'Statut'
            ])
            ->add('photo', FileType::class, [
                'label' => 'Photo (Images)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        // 'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/*'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Image File',
                    ])
                ],
                'label' => 'Photo'
            ])
            ->add('save', SubmitType::class, [
                'attr' => ['class' => 'btn btn-primary btn-block'],
                'label' => 'Sauvegarder'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Path;
use App\Entity\Todo;
use App\Form\TodoType;

class TodoController extends AbstractController
{
    #[Route('/todo', name: 'app_todo')]
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        $todos = $doctrine->getRepository(Todo::class)->findBy(['user_id' => $this->getUser()->getId()]);

        return $this->render('todo/index.html.twig', [
            'todos' => $todos,
            'msg' => $request->get('msg')
        ]);
    }

    #[Route('/todo/create', name: 'app_todo_create')]
    public function create(Request $request, SluggerInterface $slugger, ManagerRegistry $doctrine) :Response
    {
        $em = $doctrine->getManager();
        $todo = new Todo();
        $form = $this->createForm(TodoType::class, $todo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $photoFile */
            $photoFile = $form->get('photo')->getData();

            if ($photoFile) {
                $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photoFile->guessExtension();

                try {
                    $photoFile->move(
                        $this->getParameter('todo_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $todo->setPhotoSrc($newFilename);
            }

            $todo->setUserId($this->getUser()->getId());
            $em->persist($todo);
            $em->flush();

            return $this->redirectToRoute('app_todo', ['msg' => [
                'status' => 'success',
                'text' => 'Created Successfully!'
            ]]);
        }

        return $this->render('todo/create.html.twig', [
            'form' => $form,
            'error' => []
        ]);
    }

    #[Route('/todo/edit/{id}', name: 'app_todo_edit')]
    public function update(Request $request, int $id, SluggerInterface $slugger, ManagerRegistry $doctrine) :Response
    {
        $em = $doctrine->getManager();
        $fs = new Filesystem();
        $todo = $em->getRepository(Todo::class)->find($id);
        if (!$todo) {
            throw $this->createNotFoundException(
                'No item found for id '.$id
            );
        }
        if ($todo->getUserId() !== $this->getUser()->getId()) {
            throw $this->createAccessDeniedException('Access is denied');
        }

        $form = $this->createForm(TodoType::class, $todo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $photoFile */
            $photoFile = $form->get('photo')->getData();

            if ($photoFile) {
                $originalFilename = pathinfo($photoFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$photoFile->guessExtension();

                try {
                    $photoFile->move(
                        $this->getParameter('todo_directory'),
                        $newFilename
                    );
                    $fs->remove($this->getParameter('todo_directory').'/'.$todo->getPhotoSrc());
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }

                $todo->setPhotoSrc($newFilename);
            }

            $todo->setUserId($this->getUser()->getId());
            $em->persist($todo);
            $em->flush();

            return $this->redirectToRoute('app_todo', ['msg' => [
                'status' => 'success',
                'text' => 'Updated Successfully!'
            ]]);
        }

        return $this->render('todo/create.html.twig', [
            'form' => $form,
            'error' => []
        ]);
    }

    #[Route('/todo/delete/{todo}', name: 'app_todo_delete')]
    public function delete(Todo $todo, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        if ( $todo->getPhotoSrc() ) {
            $fs = new Filesystem();
            try {
                $fs->remove($this->getParameter('todo_directory').'/'.$todo->getPhotoSrc());
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }
        }
        $em->remove($todo);
        $em->flush();

        return $this->redirectToRoute('app_todo', ['msg' => [
            'status' => 'success',
            'text' => 'Deleted Successfully!'
        ]]);
    }

}

templates/todo/create.html.twig
{% extends 'base.html.twig' %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block content %}
    <div class="row my-4">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Todo Lists</h1>
        </div>
    </div>

    <div class="card">    
        <div class="card-header">
            <h1 class="card-title">Create Todo</h1>
        </div>
        <div class="card-body">
            {% if error %}
                <div class="notification alert alert-error" role="alert">
                    {{ error['messageData'] }}
                </div>
            {% endif %}

            {{ form_start(form) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}

    <div class="row my-4">
        <div class="col-sm-6">
            <h1 class="m-0 text-dark">Mes tâches</h1>
        </div>
        <div class="col-sm-6">
            <a href="{{ path('app_todo_create') }}" type="button" class="btn btn-outline-primary float-right">
                <i class="fa fa-plus"></i> Ajouter une tâche
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <style>
                .table td {
                    vertical-align: middle;
                }
                .todo-photo {
                    width: 50px;
                    height: 50px;
                    border-radius: 50%;
                }
            </style>
            {% if msg %}
                <div class="alert alert-{{ msg.status }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    {{ msg.text }}
                </div>
            {% endif %}
            <table id="todos" class="table table-hover">
                <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Statut</th>
                        <th>Date de fin</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo in todos %}
                        <tr class="todo-row-{{todo.id}}">
                            <td class="title">
                                <div class="row">
                                    {% if todo.photoSrc %}
                                    <div class="mr-2">
                                        <img class="todo-photo" src="{{ asset('uploads/todo/' ~ todo.photoSrc) }}" alt="Todo Image" >
                                    </div>
                                    {% endif %}
                                    <div>
                                        <div>{{ todo.title }}<div>
                                        <div><small>{{ todo.description }}<small><div>
                                    </div>
                                </div>
                            </td>
                            <td class="status">
                                {% if todo.status == 'pending' %}
                                    <span class="badge bg-success">To do</span>
                                {% endif %}
                                {% if todo.status == 'inprogress' %}
                                    <span class="badge bg-danger">In progress</span>
                                {% endif %}
                                {% if todo.status == 'completed' %}
                                    <span class="badge bg-info">Completed</span>
                                {% endif %}
                            </td>
                            
                            <td class="end_date">{{ todo.endDate | date('d/m/Y') }}</td>
                            <td>
                                <a href="{{ path('app_todo_edit', {id: todo.id}) }}" class="fas fa-edit mr-2"></a>
                                <a href="javascript: void(0)" class="fas fa-trash btn-delete" data-url="{{ path('app_todo_delete', {todo: todo.id}) }}"></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Confirm</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure to delete this item?</p>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary modal-confirm">Confirm</button>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block script %}
    <script>
        var seletedItemUrl = null;
        $('.btn-delete').click(function() {
            $('#modal').modal();
            seletedItemUrl = $(this).data('url');
        })
        $('.modal-confirm').click(function() {
            window.location.assign(seletedItemUrl);
        })
    </script>
{% endblock %}